version: '3.7'
services:
  fail2rest:
    image: docker.netsoc.co/public/fail2rest:dev-env
    container_name: fail2rest
    ports: 
      - 8080:8080
    depends_on:
      - consul
    volumes:
      - /var/run/fail2ban:/var/run/fail2ban
    environment:
      - CONSUL_HOST=netsoc-consul:8500